// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA24dKUfQB3o9MaVAjsV1cWL10gJOjTP5k',
    appId: '1:586882765354:web:8f44e95af6886cba2d6953',
    messagingSenderId: '586882765354',
    projectId: 'ukeep-a63d9',
    authDomain: 'ukeep-a63d9.firebaseapp.com',
    storageBucket: 'ukeep-a63d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFK10CNGyAXJodwvX6zP0qg9CE6FEt33Y',
    appId: '1:586882765354:android:ae914a8d5407d6f02d6953',
    messagingSenderId: '586882765354',
    projectId: 'ukeep-a63d9',
    storageBucket: 'ukeep-a63d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHj6wAqPq-nesPMLAaZWsE_YSvMW7_tAw',
    appId: '1:586882765354:ios:1120cb7f864ba6742d6953',
    messagingSenderId: '586882765354',
    projectId: 'ukeep-a63d9',
    storageBucket: 'ukeep-a63d9.appspot.com',
    iosClientId: '586882765354-hmp1gp95kf2f100hfs4b9n2t3j6efpho.apps.googleusercontent.com',
    iosBundleId: 'com.example.ukeep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHj6wAqPq-nesPMLAaZWsE_YSvMW7_tAw',
    appId: '1:586882765354:ios:1120cb7f864ba6742d6953',
    messagingSenderId: '586882765354',
    projectId: 'ukeep-a63d9',
    storageBucket: 'ukeep-a63d9.appspot.com',
    iosClientId: '586882765354-hmp1gp95kf2f100hfs4b9n2t3j6efpho.apps.googleusercontent.com',
    iosBundleId: 'com.example.ukeep',
  );
}
